services:
  postgresdb:
    container_name: ecomapp_postges
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ecomapp
      POSTGRES_PASSWORD: ecomapp
      POSTGRES_DB: ecomapp
      PG_DATA: /var/lib/postgresql/data
    networks:
      - ecomapp-net
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      -5432:5432



  pgadmin:
    container_name: ecomapp_pgadmin4
    image: dpage/pgadmin4:7
    depends_on:
      - postgresdb
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - ecomapp-net
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mongodb:
    container_name: ecomapp_mongo_db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ecomapp
      - MONGO_INITDB_ROOT_PASSWORD=ecomapp

  mongo-express:
    image: mongo-express
    container_name: ecomapp_mongo_express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ecomapp
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ecomapp
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mail-dev:
    container_name: ecomapp-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  ecomapp-net:
    driver: bridge

volumes:
  postgres:
  pgadmin-data:
  mongo: